core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapps.accounts.emails import (
    CustomPasswordResetConfirmView,
    CustomPasswordResetView,
)

urlpatterns = [
    path("", include("mainapps.home.urls", namespace="home")),
    path("admin/", admin.site.urls),
    path("accounts/", include("mainapps.accounts.urls", namespace="accounts")),
    # path("video/", include("mainapps.video.urls", namespace="video")),
    path("text/", include("mainapps.vidoe_text.urls", namespace="video_text")),
    path(
        "auth/password_reset/", CustomPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "auth/reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("auth/", include("django.contrib.auth.urls")),  # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapps/accounts/api/urls.py
urlpatterns = []

mainapps/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="signin"),
    path("logout/", views.logout_view, name="logout"),
    path("contact/", views.contact_view, name="contact"),
    path("verify/<str:token>", views.verify, name="verify"),
    path("stripe-webhook", views.stripe_webhook, name="stripe_webhook"),
    path("subscribe/<str:price_id>", views.subscribe, name="subscribe"),
    path("manage-subscription", views.manage_subscription, name="manage_subscription"),
    path(
        "upgrade-subscription/<str:price_id>",
        views.upgrade_subscription,
        name="upgrade_subscription",
    ),
    path(
        "downgrade-subscription",
        views.downgrade_subscription,
        name="downgrade_subscription",
    ),
    path("add-credits", views.add_credits, name="add_credits"),
    path("add-credits-success", views.add_credits_success, name="add_credits_success"),
    path("add-credits-cancel", views.add_credits_cancel, name="add_credits_cancel"),
    path("billing-portal", views.billing_portal, name="billing_portal"),
    path("cancel-subscription", views.cancel_subscription, name="cancel_subscription"),

    # terms

     path("terms-conditions/", views.terms_conditions_view, name="terms_conditions"),
     path("privacy-policy/", views.privacy_policy_view, name="privacy_policy"),
     path("refund-policy/", views.refund_policy_view, name="refund_policy"),
     path("affiliate-terms/", views.affiliate_programs_terms_view, name="affiliate_terms"),    
]

mainapps/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.home, name="home"),
    path("terms-and-conditions/", views.terms_and_conditions, name="terms_conditions"),
    path("privacy-policy/", views.privacy_and_policy, name="privacy_policy"),
    path("refund-policy/", views.refund_and_policy, name="refund_policy"),
    path("affiliate-terms/", views.affiliate_programs_terms, name="affiliate_terms"),
]

mainapps/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class Plan(models.Model):
    stripe_price_id = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    price_per_vsl = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    vsl_limit = models.IntegerField(default=0)


class StripeCustomer(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, null=True)
    stripe_customer_id = models.CharField(max_length=255)


class Subscription(models.Model):
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=255, null=True)
    customer = models.ForeignKey(StripeCustomer, on_delete=models.CASCADE, null=True)
    credits = models.IntegerField(default=0)
    current_period_end = models.IntegerField(default=0)



# class CustomUserManager(BaseUserManager):
#     def create_user(self, email, password=None, **extra_fields):
#         if not email:
#             raise ValueError("The Email field must be set")
#         email = self.normalize_email(email)
#         user = self.model(email=email, **extra_fields)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user

#     def create_superuser(self, email, password=None, **extra_fields):
#         extra_fields.setdefault("is_staff", True)
#         extra_fields.setdefault("is_superuser", True)
#         return self.create_user(email, password, **extra_fields)

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if not extra_fields.get("is_staff"):
            raise ValueError("Superuser must have is_staff=True.")
        if not extra_fields.get("is_superuser"):
            raise ValueError("Superuser must have is_superuser=True.")

        user = self.create_user(email, password, **extra_fields)

        try:
            admin_plan = Plan.objects.get(id=4) 
            stripe_customer = StripeCustomer.objects.create(user=user, stripe_customer_id=f"admin_{user.id}")
            subscription = Subscription.objects.create(
                plan=admin_plan,
                stripe_subscription_id=f"sub_admin_{user.id}",
                customer=stripe_customer,
                credits=admin_plan.vsl_limit,  
            )

            user.subscription = subscription
            user.save()
        except Plan.DoesNotExist:
            return user
            # raise ValueError("Admin plan with ID=4 does not exist. Please create it first.")


        return user

class User(AbstractUser):
    email = models.EmailField(unique=True, null=False, blank=False)
    api_key = models.CharField(max_length=255, blank=True, null=True)
    verification_token = models.CharField(max_length=100, blank=True, null=True)
    subscription = models.OneToOneField(Subscription,related_name='user', on_delete=models.SET_NULL, null=True, blank=True)  
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        self.username = self.email
        super().save(*args, **kwargs)

    def can_generate_video(self):
        return self.subscription.credits >= 1

mainapps/accounts/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate,
    login as auth_login,
    logout,
    get_user_model,
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from mainapps.accounts.emails import send_html_email2
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from .models import Plan, Subscription, StripeCustomer
import stripe
import uuid


@csrf_exempt
def contact_view(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        message = request.POST.get("message")

        subject = f"New Contact Form Submission from {first_name} {last_name}"
        email_body = f"First Name: {first_name}\nLast Name: {last_name}\nEmail: {email}\nMessage:\n{message}"

        try:
            send_mail(
                subject,
                email_body,
                settings.DEFAULT_FROM_EMAIL,
                [
                    settings.DEFAULT_FROM_EMAIL,
                ],
            )
            return JsonResponse(
                {"success": True, "message": "Your message has been sent successfully!"}
            )
        except Exception as e:
            return JsonResponse(
                {"success": False, "message": f"An error occurred: {str(e)}"}
            )

    return JsonResponse({"success": False, "message": "Invalid request method."})


def logout_view(request):
    logout(request)

    messages.success(request, "You Have Been Successfully Logged Out.")

    return redirect("/")


def login(request):
    if request.user.is_authenticated:
        return redirect("/text")

    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        user = authenticate(request, username=email, password=password)

        if user is not None:
            if user.verification_token is None:
                auth_login(request, user)

                try:
                    return redirect(request.session.get("next"))
                except:
                    return redirect("/text")
            else:
                messages.error(
                    request,
                    "Your Email Address Is Not Verified. Please Verify Your Email Before Logging In.",
                )
        else:
            messages.error(request, "Invalid Username or Password. Please Try Again.")

    next = request.GET.get("next", "")
    request.session["next"] = next
    return render(
        request,
        "lead-maker/accounts/login.html",
    )


def register(request):
    
    if request.method == "POST":
        stripe.api_key = settings.STRIPE_SEC_KEY

        checkout_session_id = request.POST.get("session_id")

        name = request.POST.get("name")
        email = request.POST.get("email")
        password1 = request.POST.get("password")
        password2 = request.POST.get("Confirmpassword")

        if len(password1) < 6:
            messages.error(request, "At Least 6 Characters Are Required")
            return render(
                request,
                "lead-maker/accounts/signup.html",
                context={"session_id": checkout_session_id},
            )

        if password1 != password2:
            messages.error(request, "Passwords Do Not Match.")
            return render(
                request,
                "lead-maker/accounts/signup.html",
                context={"session_id": checkout_session_id},
            )

        User = get_user_model()
        if User.objects.filter(email=email).exists():
            messages.error(request, "This Email Is Already Registered.")
            return render(
                request,
                "lead-maker/accounts/signup.html",
                context={"session_id": checkout_session_id},
            )

        user = User.objects.create_user(email=email, password=password1)
        user.first_name = name
        user.save()

        if checkout_session_id is None:
            free_plan = Plan.objects.get(id=3)
            customer = stripe.Customer.create(
                email=user.email,
                name=user.first_name,
            )
            stripe_customer = StripeCustomer(user=user, stripe_customer_id=customer.id)
            stripe_customer.save()
            subscription = Subscription(
                plan=free_plan,
                credits=1,
                customer=stripe_customer,
                stripe_subscription_id=None,
            )
            subscription.save()
            user.subscription = subscription

            verification_token = str(uuid.uuid4())
            user.verification_token = verification_token

            user.save()

            send_html_email2(
                subject="Welcome to LeadEditor.io – Verify Your Email To Continue",
                message=None,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to_email=user.email,
                html_file="accounts/verification.html",
                context={
                    "first_name": user.first_name,
                    "verification_url": settings.DOMAIN_NAME
                    + reverse("accounts:verify", kwargs={"token": verification_token}),
                },
            )

            return render(
                request,
                "lead-maker/accounts/signup.html",
                context={"price_id": "free", "success": True},
            )
        else:
            checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
            stripe_customer_id = checkout_session.customer
            subscription_id = checkout_session.get("subscription")
            if subscription_id:
                subscription = stripe.Subscription.retrieve(subscription_id)
                price_id = subscription["items"]["data"][0]["price"]["id"]
                print("Price ID:", price_id)
                customer_id = 0
                plan=Plan.objects.get(stripe_price_id=price_id)
                try:
                    customer = StripeCustomer.objects.get(
                        stripe_customer_id=stripe_customer_id
                    )

                    if customer is not None:
                        customer.user = user
                        customer.save()

                        customer_id = customer.id
                except StripeCustomer.DoesNotExist:
                    new_customer = StripeCustomer(
                        user=user, stripe_customer_id=stripe_customer_id
                    )
                    new_customer.save()

                    customer_id = new_customer.id

                try:

                    subscription = Subscription.objects.create(
                    plan=plan,
                    credits=plan.vsl_limit,
                    customer=new_customer,
                    stripe_subscription_id=subscription_id,
                    )   
                    user.subscription = subscription
                    user.save()

                except Exception as _:
                    messages.error(request, f"Subscription Failed. Please Try Again Later. {_}")
                    return redirect(f'/accounts/register/?session_id={checkout_session_id}'
                    )

                send_html_email2(
                    subject="Welcome to LeadEditor.io",
                    message=None,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to_email=user.email,
                    html_file="accounts/welcome.html",
                    context={
                        "user_name": user.first_name,
                        "login_url": settings.DOMAIN_NAME + reverse("video_text:add_text"),
                    },
                )

                auth_login(request, user)
                return redirect(reverse("video_text:add_text"))
            return redirect(f'/accounts/register/?session_id={checkout_session_id}')
            
    elif request.method == "GET":
        stripe.api_key = settings.STRIPE_SEC_KEY

        checkout_session_id = request.GET.get("session_id")
        if checkout_session_id and request.user.is_authenticated:
            user= request.user
            
            checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
            stripe_customer_id = checkout_session.customer
            checkout_session = stripe.checkout.Session.retrieve(checkout_session_id)
            stripe_customer_id = checkout_session.customer
            subscription_id = checkout_session.get("subscription")
            if subscription_id:
                subscription = stripe.Subscription.retrieve(subscription_id)
                price_id = subscription["items"]["data"][0]["price"]["id"]
                print("Price ID:", price_id)
                customer_id = 0
                plan=Plan.objects.get(stripe_price_id=price_id)
                try:
                    customer = StripeCustomer.objects.get(
                        stripe_customer_id=stripe_customer_id
                    )

                    if customer is not None:
                        customer.user = user
                        customer.save()

                        customer_id = customer.id
                except StripeCustomer.DoesNotExist:
                    new_customer = StripeCustomer(
                        user=user, stripe_customer_id=stripe_customer_id
                    )
                    new_customer.save()
                    customer=new_customer
                    customer_id = new_customer.id

                try:
                    subscription = Subscription.objects.create(
                    plan=plan,

templates/lead-maker/accounts/affiliate-terms.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block more_css %}

<style>
    .container-two {
      width: 80%;
      margin: 70px auto;
      padding: 20px;
      
    }

    .h1-style {
      color: #333;
      max-width: 100%;
      margin: 20px 0;
      font-size: 4.8rem;

    }

    .h2-style {
      color: #333;
      max-width: 100%;
      margin: 20px 0;
      font-size: 2.2rem!important;

    }

    .p-style {
      margin: 15px 0;
      max-width: 100%;
      padding: 0 0;
    }

    .ul-lst {
      list-style-type: square;
      padding-left: 20px;
      /* color:black; */
      
    }
    .ul-lst li::marker {
      color:black;
}

    .ul-lst li {
      margin: 10px 0;
      color: #646a69;
      font-size: 1.5rem;
    }

    .link-st {
      color: #0066cc;
      text-decoration: none;
    }

    .link-st:hover {
      text-decoration: underline;
    }


    @media only screen and (min-width: 1200px) {
        h2 {
            font-size: 4.8rem;
            letter-spacing: normal;
            margin-bottom: 30px;
        }
    }
    
    @media only screen and (min-width: 992px) {
        h2 {
            font-size: 3.6rem;
            letter-spacing: normal;
            margin-bottom: 30px;
        }
    }
  </style>

{% endblock more_css %}




{% block content %}

<header class="header">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid justify-content-between">
                <a class="navbar-brand" href="{% url 'accounts:home' %}">
                    <img src="{% static 'images/logo.svg' %}" alt="LeadEditor.io" class="img-fluid" />
                </a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse flex-grow-0" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="#products">Product</a>
                        <a class="nav-link" href="#how-it-work">How it Works</a>
                        <a class="nav-link" href="#portfolio">Portfolio</a>
                        <a class="nav-link" href="#pricing">Pricing</a>
                        <a class="nav-link" href="#contact">Contact</a>
                    </div>
                    <div class="header-profile d-flex align-items-center d-none d-lg-flex">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'accounts:login' %}" class="btn btn-login">Login</a>
                    {% endif  %}
                        <a href="{% url 'submitSubtitle' %}" class="btn get-start">
                            Get Started
                            <img class="btn-arrow" src="{% static 'images/btn-arrow.svg' %}" alt="arrow" />
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>

<div class="container" style="margin-top: 130px; margin-bottom: 130px;">
  <h1 class="h1-style">Affiliate Program Terms for LeadEditor.io</h1>

  <h2 class="h2-style">1. Introduction</h2>
  <p class="p-style">
    The LeadEditor.io Affiliate Program allows you to earn a <b>30% recurring commission</b> on customer subscriptions generated through your unique referral link.
  </p>

  <h2 class="h2-style">2. Eligibility and Enrollment</h2>
  <p class="p-style">
    Affiliates must complete an application and agree to these terms. Membership in the affiliate program is at the discretion of LeadEditor.io and may be revoked for violations of these terms.
  </p>

  <h2 class="h2-style">3. Commission Structure</h2>
  <p class="p-style"><b>Payout Rate:</b> Affiliates earn a <b>30% commission</b> on recurring customer payments.</p>
  <p class="p-style"><b>Payout Schedule:</b> Commissions are paid monthly, provided a minimum payout threshold is reached.</p>

  <h2 class="h2-style">4. Affiliate Responsibilities</h2>
  <p class="p-style">
    Affiliates agree to promote LeadEditor.io responsibly, following ethical guidelines, and avoiding misleading claims or unauthorized branding use.
  </p>

  <h2 class="h2-style">5. Termination of Affiliate Status</h2>
  <p class="p-style">
    Affiliates may be removed from the program for violating these terms or misusing affiliate marketing guidelines. Upon termination, no further commissions will be earned.
  </p>

  <h2 class="h2-style">Contact Us</h2>
  <p class="p-style">
    For further questions or information, please contact <a class="link-st" href="mailto:support@LeadEditor.io">support@LeadEditor.io</a>.
  </p>
</div>

  





{% include "includes/footer.html" %}

<script>
    function  sendPaymentRequest(formname){
        document.getElementById(formname).submit();
    }
</script>

<!-- Page Wrapper End -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="{% static 'js/custom.js' %}"></script>                 


{% endblock content %}

templates/lead-maker/accounts/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>LeadEditor.io</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'lead-maker/favicon.svg' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'lead-maker/css/global.css' %}" media="screen" />
    <link rel="stylesheet" type="text/css" href="{% static 'lead-maker/css/style.css' %}" media="screen" />
    <link rel="stylesheet" type="text/css" href="{% static 'lead-maker/css/responsive.css' %}" media="screen" />
    {% block more_css %}{% endblock more_css %}
  </head>
<body>


      
        {% block content %}

        <!-- signup and login forms go here -->

        {% endblock content %}



    <script src="{% static 'lead-maker/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lead-maker/js/main.js' %}"></script>
</body>
</html>

templates/lead-maker/accounts/email_verification.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/lead-maker/accounts/login.html
{% extends 'lead-maker/accounts/base.html' %}
{% block content %}
{% load static %}

<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'home:home' %}">
          <img src="{% static 'lead-maker/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
{% include "lead-maker/accounts/new_messages.html" %}
<section class="login-sec">
    <div class="login-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'home:home' %}">
                <img src="{% static 'lead-maker/images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

       

        <!-- Title -->
        <h5 class="login-title text-center">Sign in</h5>

        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="email"  style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 9px; font-family: 'Plus Jakarta Sans', sans-serif;" >Email address:</label>
                <input type="email" name="email"  placeholder="Email" class="form-control" id="email" aria-describedby="emailHelp">
            </div>

            <!-- Password Input -->
            <div class="mb-3">
                <label for="password" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 9px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="password" placeholder="Password" class="form-control" id="password">
                    <span class="show-icn" onclick="togglePasswordVisibility('password')">
                        <img src="{% static 'lead-maker/images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
                <a href="/auth/password_reset" class="forget-login">Forgot password?</a>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary get-start">Sign in</button>
        </form>

    </div>
        <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>

{% endblock content %}

templates/lead-maker/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <h2 class="form-title">Password reset complete</h2>
            <p>Your password has been set. You may go ahead and log in now.</p>

            <p class="loginhere">
                <a href="{% url 'accounts:signin' %}" class="loginhere-link">Login here</a>
            </p>
        </div>
    </div>
</section>

{% endblock content %}

templates/lead-maker/accounts/password_reset_form.html
{% extends 'lead-maker/accounts/base.html' %}
{% block content %}
{% load static %}
<style>
.error {
    color: red;
    font-size: 0.9em;
    margin-top: 8px;
}

    </style>
<header class="admin-header">
  <div class="container">
    <div class="header-two">
      <div class="vsl-logo text-center">
        <a href="{% url 'home:home' %}">
          <img src="{% static 'lead-maker/images/logo.svg' %}" class="img-fluid" alt="Logo" />
        </a>
      </div>
    </div>
  </div>
</header>
<section class="login-sec">
    <div class="register-container">
        <!-- Logo Section -->
        <div class="vsl-logo text-center">
            <a href="{% url 'home:home' %}">
                <img src="{% static 'lead-maker/images/logo-dark.svg' %}" alt="LeadMaker Logo">
            </a>
        </div>

        <!-- Title -->
        <div class="payment-message">
            <h1>Reset Your password </h1>
        </div>
        <!-- Login Form -->
        <form method="POST" id="login-form" class="form-block">
            {% csrf_token %}
            <!-- Password Input -->
            {% if form.non_field_errors %}
            <div class="error">
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
   
            <div class="mb-3">
                <label for="new_password1" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Password:</label>
                <div class="pwd-input">
                    <input type="password" name="new_password1" placeholder="Password" class="form-control" id="new_password1">
                    <span class="show-icn" onclick="togglePasswordVisibility('new_password1')">
                        <img src="{% static 'lead-maker/images/eye.svg' %}" alt="Toggle Password Visibility">
                    </span>
                </div>
            </div>
            <div class="mb-3" >
                <label for="new_password2" style="font-size: 1.8rem; font-weight: 600; color: #344054; margin-bottom: 12px; font-family: 'Plus Jakarta Sans', sans-serif;">Confirm Password:</label>
                <div class="pwd-input">
                    <input type="password" name="new_password2" placeholder="Confirm Password" class="form-control" id="new_password2">
                </div>
            </div>

            <!-- Submit Button -->
            <button  type="submit" class="btn btn-primary get-start" style="margin-top: 30px">Reset Password</button>
        </form>

    </div>
    <script>
    function togglePasswordVisibility(id) {
        const passwordField = document.getElementById(id);
        const isPasswordVisible = passwordField.type === "text";
        passwordField.type = isPasswordVisible ? "password" : "text";
    }
</script>
</section>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>



{% endblock content %}

templates/lead-maker/accounts/password_reset_sent.html
{% extends 'accounts/base.html' %}
{% block content %}

<section class="signup">
    <div class="container">
        <div class="signup-content">
            <h2 class="form-title">Password reset sent</h2>

            <p style="">We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

            <p style="">If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

            <p class="loginhere mt-3">
                Go back to <a href="{% url 'accounts:signin' %}" class="loginhere-link">Login here</a>
            </p>

        </div>
    </div>
</section>

{% endblock content %}